config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :categories do
    resources :suscriptions, except: [:index, :show]
  end
  resources :leads

  root 'leads#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :suscriptions
  validates :name, uniqueness: true
end

app/models/lead.rb
class Lead < ActiveRecord::Base

  has_many :messages, class_name: "Ahoy::Message", as: :user

	has_many :lead_suscriptions
	has_many :suscriptions, :through => :lead_suscriptions
  has_many :categories
	validates :name, :lastname, :company, :industry, presence: true
  validates :email, uniqueness: true

end

app/models/lead_suscription.rb
class LeadSuscription < ActiveRecord::Base
  belongs_to :lead
  belongs_to :suscription
end

app/models/suscription.rb
class Suscription < ActiveRecord::Base
	has_many :lead_suscriptions
	has_many :leads, :through => :lead_suscriptions

	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @suscription = Suscription.new
    @suscriptions = @category.suscriptions
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: [:show, :edit, :update, :destroy]

  # GET /leads
  # GET /leads.json
  def index
    @leads = Lead.all
    @categories = Category.all
  end

  # GET /leads/1
  # GET /leads/1.json
  def show
    @category = Category.new
    @categories = @lead.categories
  end

  # GET /leads/new
  def new
    @lead = Lead.new
  end

  # GET /leads/1/edit
  def edit
  end

  # POST /leads
  # POST /leads.json
  def create
    @lead = Lead.new(lead_params)

    respond_to do |format|
      if @lead.save
        format.html { redirect_to @lead, notice: 'Lead was successfully created.' }
        format.json { render :show, status: :created, location: @lead }
      else
        format.html { render :new }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leads/1
  # PATCH/PUT /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        format.html { redirect_to @lead, notice: 'Lead was successfully updated.' }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @lead.destroy
    respond_to do |format|
      format.html { redirect_to leads_url, notice: 'Lead was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @lead = Lead.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lead_params
      params.require(:lead).permit(:email, :name, :lastname, :company, :role, :area, :industry, :phone, :module, :status, :category)
    end
end

app/controllers/suscriptions_controller.rb
class SuscriptionsController < ApplicationController
  before_action :set_suscription, only: [:show, :edit, :update, :destroy]

  # GET /suscriptions/1/edit
  def edit
  end

  # POST /suscriptions
  # POST /suscriptions.json
  def create
    @category = Category.find(params[:category_id])
    @suscription = Suscription.new(suscription_params)
    @suscription.category = @category

    respond_to do |format|
      if @suscription.save
        format.html { redirect_to @category, notice: 'Suscription was successfully created.' }
        format.json { render :show, status: :created, location: @suscription }
      else
        format.html { render :new }
        format.json { render json: @suscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suscriptions/1
  # PATCH/PUT /suscriptions/1.json
  def update
    respond_to do |format|
      if @suscription.update(suscription_params)
        format.html { redirect_to @suscription, notice: 'Suscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @suscription }
      else
        format.html { render :edit }
        format.json { render json: @suscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suscriptions/1
  # DELETE /suscriptions/1.json
  def destroy
    @category = Category.find(params[:category_id])
    @suscription.destroy
    respond_to do |format|
      format.html { redirect_to @category, notice: 'Suscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_suscription
      @suscription = Suscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def suscription_params
      params.require(:suscription).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/suscriptions_helper.rb
module SuscriptionsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<h2>New Suscription</h2>

<%= render :partial => "suscriptions/form" %>

<h2>Suscripciones</h2>

<% @suscriptions.each do |suscription| %>
  <p><%= suscription.name %> <%= link_to 'X', category_suscription_path(@category, suscription), method: :delete %></p>
<% end %>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/leads/_form.html.erb
<%= form_for(@lead) do |f| %>
<% if @lead.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

  <ul>
    <% @lead.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div id="main-wrapper" class="container">
 <div class="row">
  <div class="col-md-6">
    <div class="panel panel-white">
      <div class="panel-body">
        <form>
          <div class="form-group">

            <div class="field">
              <%= f.label :email %><br>
              <%= f.text_field :email %>
            </div>
            <div class="field">
              <%= f.label :nombre %><br>
              <%= f.text_field :name %>
            </div>
            <div class="field">
              <%= f.label :apellido %><br>
              <%= f.text_field :lastname %>
            </div>
            <div class="field">
              <%= f.label :empresa %><br>
              <%= f.text_field :company %>
            </div>
            <div class="field">
              <%= f.label :cargo %><br>
              <%= f.text_field :role %>
            </div>
            <div class="field">
              <%= f.label :area %><br>
              <%= f.text_field :area %>
            </div>
            <div class="field">
              <%= f.label :mercado %><br>
              <%= f.text_field :industry %>
            </div>
            <div class="field">
              <%= f.label :teléfono %><br>
              <%= f.number_field :phone %>
            </div>
            <div class="field">
              <%= f.label :modulo %><br>
              <%= f.text_field :module %>
            </div>
            <div class="field">
              <%= f.label :status %><br>
              <%= f.text_field :status %>
            </div>
            <div class="field">
              <%= f.label :tipo_de_email %><br>
              <%#= text_field :category, :name %> 
              <%= f.select :categories, Category.all.map{|categories| [categories.name]}, {multiple: true} %>


            </div>
            <div class="actions">
              <%= f.submit %>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
</div>
<% end %>

app/views/leads/edit.html.erb
<div class="page-title">
<div class="container">
<h1>Editar Lead</h1>

<%= render 'form' %>

<button type="button" class="btn btn-default">
<%= link_to 'Ver', @lead %></button>

<button type="button" class="btn btn-success">
<%= link_to 'Volver', leads_path %></button>

</div>
</div>

app/views/leads/index_2.html.erb
<p id="notice"><%= notice %></p>

<div class="page-title">
  <div class="container">
   <h1>Clientes y Potenciales</h1>
 </div>

 <div id="main-wrapper" class="container">
  <div class="row">
    <div class="col-lg-3 col-md-6">
      <!-- <div class="col-md-12"> -->
      <div class="panel panel-white">
        <div class="panel-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Email</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Empresa</th>
                <th>Cargo</th>
                <th>Area</th>
                <th>Mercado</th>
                <th>Teléfono</th>
                <th>Modulos</th>
                <th>Status</th>
                <th>Tipo Email</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody class="table table-hover">
              <% @leads.each do |lead| %>
              <tr>
                <td scope="row"><%= lead.email %></td>
                <td scope="row"><%= lead.name %></td>
                <td scope="row"><%= lead.lastname %></td>
                <td scope="row"><%= lead.company %></td>
                <td scope="row"><%= lead.role %></td>
                <td scope="row"><%= lead.area %></td>
                <td scope="row"><%= lead.industry %></td>
                <td scope="row"><%= lead.phone %></td>
                <td scope="row"><%= lead.module %></td>
                <td scope="row"><%= lead.status %></td>
                <td scope="row"><%= lead.categories.name %></td>
                <td scope="row"><%= link_to 'Ver', lead %></td>
                <td scope="row"><%= link_to 'Editar', edit_lead_path(lead) %></td>
                <td scope="row"><%= link_to 'eliminar', lead, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
              <% end %>

            </tbody>
          </table>
        </div>
      </div>
      <br>
      <button type="button" class="btn btn-success">
        <%= link_to 'Añadir nuevo', new_lead_path %></button>
      </div>
    </div>
  </div>
</div>
</div>



<!--<br>
<button type="button" class="btn btn-success">
<%#= link_to 'Añadir nuevo', new_lead_path %></button> -->

app/views/leads/new.html.erb
<div class="page-title">
  <div class="container">
 <h1>Añadir nuevo</h1>

<%= render 'form' %>

<%= link_to 'Volver', leads_path %>

</div>
</div>

app/views/leads/show.html.erb
<div class="page-title">
  <div class="container">

<h1 id="notice"><%= notice %></h1>

<div id="main-wrapper" class="container">
  <div class="row">
    <div class="col-lg-3 col-md-6">
  
<p>
  <strong>Email:</strong>
  <%= @lead.email %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @lead.name %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @lead.lastname %>
</p>

<p>
  <strong>Mercado:</strong>
  <%= @lead.company %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @lead.role %>
</p>

<p>
  <strong>Area:</strong>
  <%= @lead.area %>
</p>

<p>
  <strong>Mercado:</strong>
  <%= @lead.industry %>
</p>

<p>
  <strong>Teléfono:</strong>
  <%= @lead.phone %>
</p>

<p>
  <strong>Modulo:</strong>
  <%= @lead.module %>
</p>

<p>
  <strong>Status:</strong>
  <%= @lead.status %>
</p>

<p>
  <strong>Tipo de email:</strong>
  <%= @category.name %>
</p>


<button type="button" class="btn btn-default">
<%= link_to 'Editar', edit_lead_path(@lead) %></button>

<button type="button" class="btn btn-success">
<%= link_to 'Volver', leads_path %></button>

</div>
</div>
</div>
</div>

app/views/suscriptions/_form.html.erb
<%= form_for([@category, @suscription]) do |f| %>
<% if @suscription.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@suscription.errors.count, "error") %> prohibited this suscription from being saved:</h2>

  <ul>
    <% @suscription.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div id="main-wrapper" class="container">
 <div class="row">
  <div class="col-md-6">
    <div class="panel panel-white">
      <div class="panel-body">
        <form>
          <div class="form-group">

            <div class="field">
              <%= f.label :name %><br>
              <%= f.text_field :name %>
            </div>
            <div class="actions">
              <%= f.submit %>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
</div>
<% end %>

app/views/suscriptions/edit.html.erb
<h1>Editing Suscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @suscription %> |
<%= link_to 'Back', suscriptions_path %>

app/views/suscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Suscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Create</th>
      <th>Destroy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @suscriptions.each do |suscription| %>
      <tr>
        <td><%= suscription.create %></td>
        <td><%= suscription.destroy %></td>
        <td><%= link_to 'Show', suscription %></td>
        <td><%= link_to 'Edit', edit_suscription_path(suscription) %></td>
        <td><%= link_to 'Destroy', suscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Suscription', new_suscription_path %>

app/views/suscriptions/new.html.erb
<h1>New Suscription</h1>

<%= render 'form' %>

<%= link_to 'Back', suscriptions_path %>

app/views/suscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Create:</strong>
  <%= @suscription.create %>
</p>

<p>
  <strong>Destroy:</strong>
  <%= @suscription.destroy %>
</p>

<%= link_to 'Edit', edit_suscription_path(@suscription) %> |
<%= link_to 'Back', suscriptions_path %>